module.exports={
	devServer:{
		// port:8000,
		proxy:{
			'/v2':{
				target:'https://m.wowdsgn.com',
				host:'m.wowdsgn.com',
				changeOrigin:true,
			},
			'/pages':{
				target:'https://m.wowdsgn.com',
				host:'m.wowdsgn.com',
				changeOrigin:true,
			},
			'/recommend':{
				target:'https://m.wowdsgn.com',
				host:'m.wowdsgn.com',
				changeOrigin:true,
			},
			'/itemdetail':{
				target:'https://m.wowdsgn.com',
				host:'m.wowdsgn.com',
				changeOrigin:true,
			}
		}
	}	
}
